spring:
  application:
    name: api-gateway
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: "UserEvent:com.classroom.api_gateway.UserEvent"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_ID}
            client-secret: ${OAUTH2_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            issuer-uri: https://accounts.google.com

server:
  port: 4000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
